package com.shrikant.spark.joins

import com.shrikant.spark.foundation.EnterpriseSparkSession
import org.apache.spark.sql.{DataFrame, Row, SparkSession}
import org.apache.spark.sql.functions._

/**
 * Module 1.6.11 — AQE Join Conversion
 *
 * Demonstrates how Adaptive Query Execution (AQE) can change the join
 * strategy at runtime based on statistics collected after shuffle stages.
 *
 * Experiment goal:
 *   Initial plan  : Sort Merge Join
 *   Runtime stats : Customer dimension is small enough to broadcast
 *   Final plan    : Broadcast Hash Join
 *
 * This experiment intentionally disables static broadcasting so that the
 * initial plan is not already a Broadcast Hash Join. AQE is then allowed
 * to make the broadcast decision after runtime statistics become available.
 */
object AQEJoinConversionExperiment {

  def main(args: Array[String]): Unit = {

    // -----------------------------------------------------------------------
    // 1. Parse experiment parameters
    // -----------------------------------------------------------------------

    // Number of shuffle partitions used by the initial shuffle stages.
    val shufflePartitions =
      if (args.nonEmpty) args(0).toInt else 20

    // Runtime broadcast threshold used by AQE.
    // Default = 10 MiB.
    //
    // Example:
    //   10 MiB = 10 * 1024 * 1024 bytes
    val adaptiveBroadcastThreshold =
      if (args.length > 1) args(1).toLong
      else 10L * 1024 * 1024

    // -----------------------------------------------------------------------
    // 2. Create the Spark session
    // -----------------------------------------------------------------------

    val spark: SparkSession =
      EnterpriseSparkSession.create(
        "AQE Join Conversion Experiment",
        "dev"
      )

    // -----------------------------------------------------------------------
    // 3. Configure Spark for the AQE experiment
    // -----------------------------------------------------------------------

    // Control the number of partitions generated by shuffle operations.
    spark.conf.set(
      "spark.sql.shuffle.partitions",
      shufflePartitions.toString
    )

    // Enable Adaptive Query Execution.
    //
    // AQE allows Spark to reconsider parts of the physical plan after
    // runtime statistics become available.
    spark.conf.set(
      "spark.sql.adaptive.enabled",
      "true"
    )

    // IMPORTANT:
    //
    // Disable static broadcast join selection.
    //
    // Without this setting, Spark could see that customerDf is small
    // during initial planning and immediately choose Broadcast Hash Join.
    //
    // Setting this to -1 forces the initial plan away from static
    // broadcasting, allowing us to demonstrate AQE performing the
    // conversion later.
    spark.conf.set(
      "spark.sql.autoBroadcastJoinThreshold",
      "-1"
    )

    // Allow AQE to consider broadcasting a relation after runtime
    // statistics are available.
    //
    // The default value is 10 MiB.
    spark.conf.set(
      "spark.sql.adaptive.autoBroadcastJoinThreshold",
      adaptiveBroadcastThreshold.toString
    )

    // Disable AQE partition coalescing for this experiment.
    //
    // We want the experiment to focus specifically on join conversion
    // rather than simultaneously changing the number of shuffle partitions.
    spark.conf.set(
      "spark.sql.adaptive.coalescePartitions.enabled",
      "false"
    )

    // -----------------------------------------------------------------------
    // 4. Create the fact dataset
    // -----------------------------------------------------------------------
    //
    // 10 million transaction records.
    //
    // customer_id has 100,000 distinct values, meaning each customer
    // participates in approximately 100 transactions on average.
    //
    // This represents a typical large fact table joining with a
    // relatively small customer dimension.

    val factDf: DataFrame =
      spark.range(0, 10000000)
        .select(
          col("id").alias("transaction_id"),
          (col("id") % 100000).alias("customer_id"),
          (col("id") % 1000).alias("amount")
        )

    // -----------------------------------------------------------------------
    // 5. Create the customer dimension
    // -----------------------------------------------------------------------
    //
    // 100,000 customer records.
    //
    // This relation is intentionally small enough that, after Spark
    // obtains runtime statistics, AQE can determine that broadcasting it
    // is feasible.

    val customerDf: DataFrame =
      spark.range(0, 100000)
        .select(
          col("id").alias("customer_id"),
          concat(
            lit("CUSTOMER_"),
            col("id")
          ).alias("customer_name")
        )

    // -----------------------------------------------------------------------
    // 6. Define the join
    // -----------------------------------------------------------------------
    //
    // No BROADCAST, MERGE, or SHUFFLE_HASH hint is used here.
    //
    // This is important because we want Spark/AQE to make the decision.
    val joinedDf =
      factDf.join(
        customerDf,
        Seq("customer_id"),
        "inner"
      )

    println(
      s"=== Module 1.6.11 — AQE Join Conversion | " +
        s"adaptive threshold=$adaptiveBroadcastThreshold bytes ==="
    )

    // -----------------------------------------------------------------------
    // 7. Inspect the initial physical plan
    // -----------------------------------------------------------------------
    //
    // Because static broadcasting is disabled, the initial plan is
    // expected to use Sort Merge Join.
    //
    // Typical initial plan:
    //
    //   SortMergeJoin
    //      /       \
    //   Exchange  Exchange
    //      |         |
    //    Sort      Sort
    //
    // IMPORTANT:
    // explain() before execution shows the plan Spark has initially
    // generated. AQE may change this plan after runtime statistics
    // become available.

    println("Initial plan:")
    joinedDf.explain("formatted")

    // -----------------------------------------------------------------------
    // 8. Execute the join
    // -----------------------------------------------------------------------
    //
    // foreachPartition is used as the terminal action.
    //
    // We explicitly consume every Row so Spark must execute the complete
    // join rather than stopping after producing only partial output.
    val start = System.nanoTime()

    joinedDf.foreachPartition { rows: Iterator[Row] =>
      while (rows.hasNext) {
        rows.next()
      }
    }

    val seconds =
      (System.nanoTime() - start) / 1e9

    println(f"Rows joined = 10,000,000")
    println(f"Execution time = $seconds%.3f s")

    // -----------------------------------------------------------------------
    // 9. Inspect the final AQE physical plan
    // -----------------------------------------------------------------------
    //
    // After execution, AQE has access to runtime statistics from the
    // shuffle stages.
    //
    // With the default 10 MiB adaptive threshold, the customer relation
    // is expected to be recognized as small enough to broadcast.
    //
    // Expected transformation:
    //
    //   INITIAL PLAN
    //   SortMergeJoin
    //      ↓
    //   Runtime shuffle statistics
    //      ↓
    //   AQE evaluates broadcast opportunity
    //      ↓
    //   FINAL PLAN
    //   BroadcastHashJoin
    //
    // The final plan is the most important evidence for this experiment.

    println("Final plan:")
    joinedDf.explain("formatted")

    // -----------------------------------------------------------------------
    // 10. Stop Spark
    // -----------------------------------------------------------------------

    spark.stop()
  }
}
