package com.shrikant.spark.joins

import com.shrikant.spark.foundation.EnterpriseSparkSession
import org.apache.spark.sql.{DataFrame, Row, SparkSession}
import org.apache.spark.sql.functions._

/**
 * Module 1.6.10 — AQE + Join Skew
 *
 * Demonstrates how Adaptive Query Execution (AQE) detects and mitigates
 * data skew during a shuffle-based join.
 *
 * Experiment goal:
 *
 *   1. Create a highly skewed fact dataset.
 *   2. Force a Sort Merge Join.
 *   3. Enable AQE skew join optimization.
 *   4. Execute the join.
 *   5. Inspect the final adaptive plan and Spark UI.
 *
 * Expected behavior:
 *
 *   Initial Plan
 *        |
 *        v
 *   Sort Merge Join
 *        |
 *        v
 *   Shuffle partition contains a disproportionate amount of data
 *        |
 *        v
 *   AQE detects skewed partition
 *        |
 *        v
 *   AQE splits the skewed partition
 *        |
 *        v
 *   Final Plan contains:
 *       SortMergeJoin(skew=true)
 *       AQEShuffleRead
 *
 * Important:
 *
 * Increasing spark.sql.shuffle.partitions alone does NOT split records
 * belonging to the same hot key across multiple partitions.
 */
object AQESkewJoinExperiment {

  def main(args: Array[String]): Unit = {

    // -----------------------------------------------------------------------
    // 1. Parse experiment parameters
    // -----------------------------------------------------------------------

    // Number of shuffle partitions.
    //
    // This controls the number of partitions generated by the shuffle,
    // but it does not by itself eliminate a hot-key problem.
    val shufflePartitions =
      if (args.nonEmpty) args(0).toInt else 20

    // AQE skew factor.
    //
    // A shuffle partition can be considered skewed when its size is
    // significantly larger than the median partition size.
    //
    // Lower values make AQE more aggressive when identifying skew.
    val skewFactor =
      if (args.length > 1) args(1).toDouble else 2.0

    // Minimum absolute size, in bytes, for a partition to be considered
    // skewed.
    //
    // Default experiment value = 1 MiB.
    val skewThreshold =
      if (args.length > 2) args(2).toLong
      else 1048576L

    // -----------------------------------------------------------------------
    // 2. Create Spark session
    // -----------------------------------------------------------------------

    val spark: SparkSession =
      EnterpriseSparkSession.create(
        "AQE Skew Join Experiment",
        "dev"
      )

    // -----------------------------------------------------------------------
    // 3. Configure Spark
    // -----------------------------------------------------------------------

    // Number of partitions generated by shuffle operations.
    spark.conf.set(
      "spark.sql.shuffle.partitions",
      shufflePartitions.toString
    )

    // Disable static broadcast joins.
    //
    // We want to study a shuffle-based join and AQE's skew handling,
    // rather than allowing Spark to eliminate the shuffle through
    // Broadcast Hash Join.
    spark.conf.set(
      "spark.sql.autoBroadcastJoinThreshold",
      "-1"
    )

    // Enable Adaptive Query Execution.
    //
    // AQE allows Spark to make runtime decisions using statistics
    // collected during query execution.
    spark.conf.set(
      "spark.sql.adaptive.enabled",
      "true"
    )

    // Enable AQE skew join optimization.
    //
    // When Spark detects a sufficiently large shuffle partition,
    // AQE can split that partition into smaller pieces.
    spark.conf.set(
      "spark.sql.adaptive.skewJoin.enabled",
      "true"
    )

    // Configure how aggressively AQE detects skew.
    //
    // A value of 2.0 means the partition must be significantly larger
    // than the median partition size to qualify based on the factor.
    spark.conf.set(
      "spark.sql.adaptive.skewJoin.skewedPartitionFactor",
      skewFactor.toString
    )

    // Configure the minimum partition size required before AQE
    // considers a partition skewed.
    spark.conf.set(
      "spark.sql.adaptive.skewJoin.skewedPartitionThresholdInBytes",
      skewThreshold.toString
    )

    // Disable AQE partition coalescing.
    //
    // This keeps the experiment focused on skew handling rather than
    // simultaneously changing the number of shuffle partitions.
    spark.conf.set(
      "spark.sql.adaptive.coalescePartitions.enabled",
      "false"
    )

    // Encourage AQE to optimize skewed joins when applicable.
    spark.conf.set(
      "spark.sql.adaptive.forceOptimizeSkewedJoin",
      "true"
    )

    // -----------------------------------------------------------------------
    // 4. Create intentionally skewed fact data
    // -----------------------------------------------------------------------
    //
    // Total rows = 10 million.
    //
    // customer_id = 0 receives 9 million rows (90% of the dataset).
    //
    // The remaining 1 million rows are distributed across other customer
    // IDs.
    //
    // This creates a classic hot-key scenario:
    //
    //                 Fact rows
    //                     |
    //          ------------------------
    //          |                      |
    //       customer 0          other customers
    //        9 million             1 million
    //          |
    //       HOT KEY
    //
    // During the shuffle, records with the same customer_id are sent
    // to the same logical partition. Therefore, customer_id = 0 can
    // create a disproportionately large shuffle partition.

    val factDf: DataFrame =
      spark.range(0, 10000000)
        .select(
          col("id").alias("transaction_id"),

          when(
            col("id") < 9000000,
            lit(0L)
          ).otherwise(
            (col("id") % 99999) + 1
          ).alias("customer_id"),

          (col("id") % 1000).alias("amount")
        )

    // -----------------------------------------------------------------------
    // 5. Create customer dimension
    // -----------------------------------------------------------------------
    //
    // 100,000 customer records.
    //
    // The dimension is intentionally kept relatively small, but static
    // broadcasting is disabled so that the experiment remains shuffle-based.

    val customerDf: DataFrame =
      spark.range(0, 100000)
        .select(
          col("id").alias("customer_id"),
          concat(
            lit("CUSTOMER_"),
            col("id")
          ).alias("customer_name")
        )

    // -----------------------------------------------------------------------
    // 6. Define the join
    // -----------------------------------------------------------------------
    //
    // MERGE hints force Spark toward Sort Merge Join.
    //
    // This gives us a predictable shuffle-based join so that we can
    // observe AQE's skew optimization.
    //
    // Without the hint, Spark could potentially choose another strategy
    // depending on statistics and configuration.

    val joinedDf =
      factDf
        .hint("MERGE")
        .join(
          customerDf.hint("MERGE"),
          Seq("customer_id"),
          "inner"
        )

    println(
      s"=== Module 1.6.10 — AQE + Join Skew | " +
        s"parts=$shufflePartitions | " +
        s"factor=$skewFactor | " +
        s"threshold=$skewThreshold bytes ==="
    )

    // -----------------------------------------------------------------------
    // 7. Inspect the initial physical plan
    // -----------------------------------------------------------------------
    //
    // Expected initial structure:
    //
    //   SortMergeJoin
    //      /       \
    //   Exchange  Exchange
    //      |         |
    //    Sort      Sort
    //
    // At this point AQE has not yet used the runtime shuffle statistics
    // to determine which partitions are skewed.

    println("Initial physical plan:")
    joinedDf.explain("formatted")

    // -----------------------------------------------------------------------
    // 8. Execute the complete join
    // -----------------------------------------------------------------------
    //
    // foreachPartition is used as the terminal action.
    //
    // We explicitly consume every Row so that Spark executes the complete
    // join rather than only constructing the lazy DataFrame lineage.

    val start = System.nanoTime()

    joinedDf.foreachPartition { rows: Iterator[Row] =>
      while (rows.hasNext) {
        rows.next()
      }
    }

    val seconds =
      (System.nanoTime() - start) / 1e9

    println(f"Rows joined = 10,000,000")
    println(f"Execution time = $seconds%.3f s")

    // -----------------------------------------------------------------------
    // 9. Inspect the final adaptive plan
    // -----------------------------------------------------------------------
    //
    // After the shuffle stages have produced runtime statistics, AQE can
    // identify partitions that are disproportionately large.
    //
    // Expected evidence:
    //
    //   SortMergeJoin(skew=true)
    //          |
    //   AQEShuffleRead
    //
    // Spark UI should additionally show:
    //
    //   - skewed partition count
    //   - skew partition splits
    //   - partition sizes
    //   - task-level execution-time imbalance
    //
    // Important:
    //
    // AQE mitigation does not guarantee perfectly balanced execution.
    // Residual task imbalance can remain after skew splitting.

    println("Final adaptive plan:")
    joinedDf.explain("formatted")

    println(
      "Inspect final plan for skew=true/AQEShuffleRead " +
        "and Spark UI for skew splits."
    )

    // -----------------------------------------------------------------------
    // 10. Stop Spark
    // -----------------------------------------------------------------------

    spark.stop()
  }
}
